# Example .pre-commit-config.yaml
# Run `pre-commit install` after creating this file

repos:
  # Basic pre-commit sanity checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace           # Remove trailing spaces
      - id: end-of-file-fixer             # Ensure file ends with newline
      - id: check-yaml                    # Validate YAML syntax
      - id: check-json                    # Validate JSON syntax
      - id: check-added-large-files       # Warn if committing large files
      - id: detect-private-key            # Prevent committing private keys

  # Optional: format Python code using Black
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  # Optional: lint Python code using Flake8
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear]

  # Optional: format Markdown files
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.19
    hooks:
      - id: mdformat
